import type { Metadata } from "next";
import { poppins }  from "@/app/ui/fonts";
import "./globals.css";
import Footer from "./ui/components/Footer";

export const metadata: Metadata = {
  title: "Darul Najah",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased bg-background`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
